###
POST http://localhost:5000/api/v1/people/personBill HTTP/1.1
Content-Type: application/json

{
    "name": "Jean Carlos Mario",
    "lastname": "Ballesteros Zamora",
    "dni": "2354434",
    "address": {
      "city": "Manizales",
      "code_zip": 234555,
      "geo": ["345545","34332"]
    }
}

###
GET http://localhost:5000/api/v1/people HTTP/1.1

###
GET http://localhost:5000/api/v1/people/624c7c95ee832926a832f1d9 HTTP/1.1


###
PUT http://localhost:5000/api/v1/people/623be9c2ed932cfcfc7988c8 HTTP/1.1
Content-Type: application/json

{
    "name": "Jean C.",
    "lastname": "Ballesteros Zamora",
    "dni": "2354434",
    "address": {
      "city": "Manizales",
      "code_zip": 234555,
      "geo": ["345545","34332"]
    }
}


###
DELETE http://localhost:5000/api/v1/people/623be9c2ed932cfcfc7988c8 HTTP/1.1












###
POST http://localhost:5000/api/v1/superheroes/superhero HTTP/1.1
Content-Type: application/json

{
    "superhero": "Batman",
    "real_name": "Robert Pattinson",
    "features": {
      "universe": "Tierra",
      "super_powers": "Ver en la oscuridad"
    },
    "superhero_sidekick": {
      "sidekick": "Robin",
      "super_powers_sidekick": "Buen amigo"
    }
}

###
GET http://localhost:5000/api/v1/superheroes HTTP/1.1

###
GET http://localhost:5000/api/v1/superheroes/623be9f8ed932cfcfc7988d7 HTTP/1.1

###
PUT http://localhost:5000/api/v1/superheroes/623be9f8ed932cfcfc7988d7 HTTP/1.1
Content-Type: application/json

{
    "superhero": "Batman",
    "real_name": "Robert Pattinson",
    "features": {
      "universe": "Tierra",
      "super_powers": "Ver en la oscuridad"
    },
    "superhero_sidekick": {
      "sidekick": "Robin",
      "super_powers_sidekick": "Hacer nada, bro"
    }
}


###
DELETE http://localhost:5000/api/v1/superheroes/623be9f8ed932cfcfc7988d5 HTTP/1.1















###
POST http://localhost:5000/api/v1/superheroes_v2/superhero_v2 HTTP/1.1
Content-Type: application/json

{
  "superhero":"Batman",
  "realname":"Bruce Wayne",
  "superpower": "Be rich"
}


###
GET http://localhost:5000/api/v1/superheroes_v2 HTTP/1.1

###
GET http://localhost:5000/api/v1/superheroes_v2/624c84e2c9e1539b6e052231 HTTP/1.1

###
PUT http://localhost:5000/api/v1/superheroes_v2/624c7d743d99802ed4587338 HTTP/1.1
Content-Type: application/json

{
  "superhero":"Batmancito",
  "realname":"Bruce Wayneg",
  "superpower": "Be rich"
}


###
DELETE http://localhost:5000/api/v1/superheroes_v2/624c7d743d99802ed4587339 HTTP/1.1